version: '3'
services:
  app:
    build:
      context: ./frontend
    image: node_front
    restart: unless-stopped
    container_name: app
    ports:
      - "3001:3000"
    volumes:
        - ./frontend:/app
        - node_modules_front:/app/node_modules
    networks:
      - app-network
  nodejs:
    build:
      context: .
    image: node_back
    container_name: nodejs
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_HOSTNAME=db
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - node_modules_back:/app/node_modules
    networks:
      - app-network
  db:
    image: mongo:4.1.8-xenial
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    ports:
      - "27017:27017"
    volumes:
      - dbdata:/data/db
    networks:
      - app-network
    
networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  node_modules_back:
  node_modules_front: